/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GSProject;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amirul
 */
public class Grading extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public Grading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        matricInput = new javax.swing.JTextField();
        matricsTxt = new javax.swing.JLabel();
        addData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        c1CarryMark = new javax.swing.JTextField();
        c1Lbl = new javax.swing.JLabel();
        c1FinalMark = new javax.swing.JTextField();
        cm465 = new javax.swing.JLabel();
        f465 = new javax.swing.JLabel();
        c2FinalMark = new javax.swing.JTextField();
        cm501 = new javax.swing.JLabel();
        f501 = new javax.swing.JLabel();
        c2CarryMark = new javax.swing.JTextField();
        c2Lbl = new javax.swing.JLabel();
        c3FinalMark = new javax.swing.JTextField();
        cm500 = new javax.swing.JLabel();
        f500 = new javax.swing.JLabel();
        c3CarryMark = new javax.swing.JTextField();
        c3Lbl = new javax.swing.JLabel();
        c4FinalMark = new javax.swing.JTextField();
        cm554 = new javax.swing.JLabel();
        f554 = new javax.swing.JLabel();
        c4CarryMark = new javax.swing.JTextField();
        c4Lbl = new javax.swing.JLabel();
        c5FinalMark = new javax.swing.JTextField();
        cmict500 = new javax.swing.JLabel();
        fict500 = new javax.swing.JLabel();
        c5CarryMark = new javax.swing.JTextField();
        classTxt = new javax.swing.JLabel();
        c5Lbl1 = new javax.swing.JLabel();
        but_3a = new javax.swing.JRadioButton();
        but_3b = new javax.swing.JRadioButton();
        but_3c = new javax.swing.JRadioButton();
        but_3d = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(64, 23));

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        matricInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricInputActionPerformed(evt);
            }
        });

        matricsTxt.setText("Matric Number :");

        addData.setText("Add");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Matric", "CLASS", "C1 GPA", "C2 GPA", "C3 GPA", "C4 GPA", "C5 GPA", "CGPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayTable);

        c1CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1CarryMarkActionPerformed(evt);
            }
        });

        c1Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c1Lbl.setText("CSC 465");

        c1FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1FinalMarkActionPerformed(evt);
            }
        });

        cm465.setText("Carry Mark :");

        f465.setText("Final/ Test Mark :");

        c2FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2FinalMarkActionPerformed(evt);
            }
        });

        cm501.setText("Carry Mark :");

        f501.setText("Final/ Test Mark :");

        c2CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2CarryMarkActionPerformed(evt);
            }
        });

        c2Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c2Lbl.setText("ISP 501");

        c3FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3FinalMarkActionPerformed(evt);
            }
        });

        cm500.setText("Carry Mark :");

        f500.setText("Final/ Test Mark :");

        c3CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3CarryMarkActionPerformed(evt);
            }
        });

        c3Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c3Lbl.setText("ISP 500");

        c4FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4FinalMarkActionPerformed(evt);
            }
        });

        cm554.setText("Carry Mark :");

        f554.setText("Final/ Test Mark :");

        c4CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4CarryMarkActionPerformed(evt);
            }
        });

        c4Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c4Lbl.setText("CTU 554");

        c5FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5FinalMarkActionPerformed(evt);
            }
        });

        cmict500.setText("Carry Mark :");

        fict500.setText("Final/ Test Mark :");

        c5CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5CarryMarkActionPerformed(evt);
            }
        });

        classTxt.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        classTxt.setText("Class");

        c5Lbl1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c5Lbl1.setText("ICT 500");

        buttonGroup1.add(but_3a);
        but_3a.setText("CS2663A");
        but_3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_3aActionPerformed(evt);
            }
        });

        buttonGroup1.add(but_3b);
        but_3b.setText("CS2663B");

        buttonGroup1.add(but_3c);
        but_3c.setText("CS2663C");

        buttonGroup1.add(but_3d);
        but_3d.setText("CS2663D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(cm500))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cm554)
                                            .addComponent(cmict500))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c5CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c4CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c3CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cm465)
                                    .addComponent(cm501)
                                    .addComponent(c1Lbl)
                                    .addComponent(c3Lbl)
                                    .addComponent(c4Lbl)
                                    .addComponent(c5Lbl1)
                                    .addComponent(c2Lbl))))
                        .addGap(310, 310, 310)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addData)
                                .addComponent(matricInput, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matricsTxt)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(c1CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(c2CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(f500)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(c3FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(f501)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c2FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(f465)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c1FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(f554)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(c4FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(fict500)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(c5FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(classTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but_3a, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but_3b, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but_3c, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but_3d, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matricsTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matricInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c1FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f465))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c2FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f501)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cm465)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c2Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cm501))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c1CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(c2CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c3CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm500)
                            .addComponent(f500))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c4CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm554)
                            .addComponent(f554))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c5Lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c5CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c5FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmict500)
                            .addComponent(fict500)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but_3a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_3b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_3c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_3d))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(addData)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricInputActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
        double[] gpa = new double[5];   
        
        
//        Tolong buatkan validation for null or undefined text input
        if(matricInput.getText().isEmpty()|| c1CarryMark.getText().isEmpty()|| c2CarryMark.getText().isEmpty()|| c3CarryMark.getText().isEmpty() || c4CarryMark.getText().isEmpty() || c5CarryMark.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some data not key in yet!");
        }      
//        Calculate GPA members of 5
        gpa[0] = ((Integer.parseInt(c1CarryMark.getText()) + Integer.parseInt(c1FinalMark.getText())) /100) * 4 ;
        gpa[1] = ((Integer.parseInt(c2CarryMark.getText()) + Integer.parseInt(c2FinalMark.getText())) /100) * 4 ;
        gpa[2] = ((Integer.parseInt(c3CarryMark.getText()) + Integer.parseInt(c3FinalMark.getText())) /100) * 4 ;
        gpa[3] = ((Integer.parseInt(c4CarryMark.getText()) + Integer.parseInt(c4FinalMark.getText())) /100) * 4 ;
        gpa[4] = ((Integer.parseInt(c5CarryMark.getText()) + Integer.parseInt(c5FinalMark.getText())) /100) * 4 ;

        double cgpa = 0.0;
        
        for(int i=0; i<5; i++){
            cgpa += gpa[i];
        }
        
        cgpa = (cgpa/20)*4;
        
       
//       radio button code (class) 
//        this.but_3a = a;
//        
//        if(but_3a.isSelected()){
//            buttonGroup1.equals(gpa)
//        }



//        data object untuk table
        String data[] = {matricInput.getText(), Double.toString(gpa[0]), Double.toString(gpa[1]), Double.toString(gpa[2]), Double.toString(gpa[3]), Double.toString(gpa[4]), Double.toString(cgpa) };
        
//        insertion of data
        DefaultTableModel tblModel = (DefaultTableModel)displayTable.getModel();
        tblModel.addRow(data);
        
                
    }//GEN-LAST:event_addDataActionPerformed

    private void c1CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1CarryMarkActionPerformed

    private void c1FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FinalMarkActionPerformed

    private void c2FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2FinalMarkActionPerformed

    private void c2CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2CarryMarkActionPerformed

    private void c3FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3FinalMarkActionPerformed

    private void c3CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3CarryMarkActionPerformed

    private void c4FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4FinalMarkActionPerformed

    private void c4CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4CarryMarkActionPerformed

    private void c5FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5FinalMarkActionPerformed

    private void c5CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5CarryMarkActionPerformed

    private void but_3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_3aActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grading().setVisible(true);
            }
        });     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addData;
    private javax.swing.JRadioButton but_3a;
    private javax.swing.JRadioButton but_3b;
    private javax.swing.JRadioButton but_3c;
    private javax.swing.JRadioButton but_3d;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c1CarryMark;
    private javax.swing.JTextField c1FinalMark;
    private javax.swing.JLabel c1Lbl;
    private javax.swing.JTextField c2CarryMark;
    private javax.swing.JTextField c2FinalMark;
    private javax.swing.JLabel c2Lbl;
    private javax.swing.JTextField c3CarryMark;
    private javax.swing.JTextField c3FinalMark;
    private javax.swing.JLabel c3Lbl;
    private javax.swing.JTextField c4CarryMark;
    private javax.swing.JTextField c4FinalMark;
    private javax.swing.JLabel c4Lbl;
    private javax.swing.JTextField c5CarryMark;
    private javax.swing.JTextField c5FinalMark;
    private javax.swing.JLabel c5Lbl1;
    private javax.swing.JLabel classTxt;
    private javax.swing.JLabel cm465;
    private javax.swing.JLabel cm500;
    private javax.swing.JLabel cm501;
    private javax.swing.JLabel cm554;
    private javax.swing.JLabel cmict500;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel f465;
    private javax.swing.JLabel f500;
    private javax.swing.JLabel f501;
    private javax.swing.JLabel f554;
    private javax.swing.JLabel fict500;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matricInput;
    private javax.swing.JLabel matricsTxt;
    // End of variables declaration//GEN-END:variables
}
