/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GSProject;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amirul
 */
public class Grading extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public Grading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matricInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        c1CarryMark = new javax.swing.JTextField();
        c1Lbl = new javax.swing.JLabel();
        c1FinalMark = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c2FinalMark = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        c2CarryMark = new javax.swing.JTextField();
        c2Lbl = new javax.swing.JLabel();
        c3FinalMark = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c3CarryMark = new javax.swing.JTextField();
        c3Lbl = new javax.swing.JLabel();
        c4FinalMark = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        c4CarryMark = new javax.swing.JTextField();
        c4Lbl = new javax.swing.JLabel();
        c5FinalMark = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        c5CarryMark = new javax.swing.JTextField();
        c5Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(64, 23));

        matricInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricInputActionPerformed(evt);
            }
        });

        jLabel3.setText("Matric Number :");

        addData.setText("Add");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Matric", "C1 GPA", "C2 GPA", "C3 GPA", "C4 GPA", "C5 GPA", "CGPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayTable);

        c1CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1CarryMarkActionPerformed(evt);
            }
        });

        c1Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c1Lbl.setText("CSC 465");

        c1FinalMark.setSize(new java.awt.Dimension(64, 23));
        c1FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1FinalMarkActionPerformed(evt);
            }
        });

        jLabel10.setText("Carry Mark :");

        jLabel11.setText("Final/ Test Mark :");

        c2FinalMark.setSize(new java.awt.Dimension(64, 23));
        c2FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2FinalMarkActionPerformed(evt);
            }
        });

        jLabel12.setText("Carry Mark :");

        jLabel13.setText("Final/ Test Mark :");

        c2CarryMark.setSize(new java.awt.Dimension(64, 23));
        c2CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2CarryMarkActionPerformed(evt);
            }
        });

        c2Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c2Lbl.setText("ISP 501");

        c3FinalMark.setSize(new java.awt.Dimension(64, 23));
        c3FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3FinalMarkActionPerformed(evt);
            }
        });

        jLabel15.setText("Carry Mark :");

        jLabel16.setText("Final/ Test Mark :");

        c3CarryMark.setSize(new java.awt.Dimension(64, 23));
        c3CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3CarryMarkActionPerformed(evt);
            }
        });

        c3Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c3Lbl.setText("ISP 500");

        c4FinalMark.setSize(new java.awt.Dimension(64, 23));
        c4FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4FinalMarkActionPerformed(evt);
            }
        });

        jLabel18.setText("Carry Mark :");

        jLabel19.setText("Final/ Test Mark :");

        c4CarryMark.setSize(new java.awt.Dimension(64, 23));
        c4CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4CarryMarkActionPerformed(evt);
            }
        });

        c4Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c4Lbl.setText("CTU 554");

        c5FinalMark.setSize(new java.awt.Dimension(64, 23));
        c5FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5FinalMarkActionPerformed(evt);
            }
        });

        jLabel21.setText("Carry Mark :");

        jLabel22.setText("Final/ Test Mark :");

        c5CarryMark.setSize(new java.awt.Dimension(64, 23));
        c5CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5CarryMarkActionPerformed(evt);
            }
        });

        c5Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c5Lbl.setText("ICT 500");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c1CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c1FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(matricInput, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(c1Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(c3FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(c5Lbl, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(c3Lbl)
                                        .addComponent(c4Lbl, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c3CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c4CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c4FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c5CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c5FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(c2Lbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matricInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c2CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c3CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c4CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c5CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c5FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addData)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricInputActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
        double[] gpa = new double[5];
        
        
//        Tolong buatkan validation for null or undefined text input
    
//        Calculate GPA members of 5
        gpa[0] = ((Integer.parseInt(c1CarryMark.getText()) + Integer.parseInt(c1FinalMark.getText())) /100) * 4 ;
        gpa[1] = ((Integer.parseInt(c2CarryMark.getText()) + Integer.parseInt(c2FinalMark.getText())) /100) * 4 ;
        gpa[2] = ((Integer.parseInt(c3CarryMark.getText()) + Integer.parseInt(c3FinalMark.getText())) /100) * 4 ;
        gpa[3] = ((Integer.parseInt(c4CarryMark.getText()) + Integer.parseInt(c4FinalMark.getText())) /100) * 4 ;
        gpa[4] = ((Integer.parseInt(c5CarryMark.getText()) + Integer.parseInt(c5FinalMark.getText())) /100) * 4 ;

        double cgpa = 0.0;
        
        for(int i=0; i<5; i++){
            cgpa += gpa[i];
        }
        
        cgpa = (cgpa/20)*4;
        
//        radio button code (class) 
        



//        data object untuk table
        String data[] = {matricInput.getText(), Double.toString(gpa[0]), Double.toString(gpa[1]), Double.toString(gpa[2]), Double.toString(gpa[3]), Double.toString(gpa[4]), Double.toString(cgpa) };
        
//        insertion of data
        DefaultTableModel tblModel = (DefaultTableModel)displayTable.getModel();
        tblModel.addRow(data);
        
                
    }//GEN-LAST:event_addDataActionPerformed

    private void c1CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1CarryMarkActionPerformed

    private void c1FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FinalMarkActionPerformed

    private void c2FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2FinalMarkActionPerformed

    private void c2CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2CarryMarkActionPerformed

    private void c3FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3FinalMarkActionPerformed

    private void c3CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3CarryMarkActionPerformed

    private void c4FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4FinalMarkActionPerformed

    private void c4CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4CarryMarkActionPerformed

    private void c5FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5FinalMarkActionPerformed

    private void c5CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5CarryMarkActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grading().setVisible(true);
            }
        });     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addData;
    private javax.swing.JTextField c1CarryMark;
    private javax.swing.JTextField c1FinalMark;
    private javax.swing.JLabel c1Lbl;
    private javax.swing.JTextField c2CarryMark;
    private javax.swing.JTextField c2FinalMark;
    private javax.swing.JLabel c2Lbl;
    private javax.swing.JTextField c3CarryMark;
    private javax.swing.JTextField c3FinalMark;
    private javax.swing.JLabel c3Lbl;
    private javax.swing.JTextField c4CarryMark;
    private javax.swing.JTextField c4FinalMark;
    private javax.swing.JLabel c4Lbl;
    private javax.swing.JTextField c5CarryMark;
    private javax.swing.JTextField c5FinalMark;
    private javax.swing.JLabel c5Lbl;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matricInput;
    // End of variables declaration//GEN-END:variables
}
