/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GSProject;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author amirul
 */
public class Grading extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public Grading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sgrPanel = new javax.swing.JPanel();
        matricInput = new javax.swing.JTextField();
        matricsTxt = new javax.swing.JLabel();
        addDataBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        LogOutBtn = new javax.swing.JButton();
        markPanel = new javax.swing.JPanel();
        fm2 = new javax.swing.JLabel();
        c2CarryMark = new javax.swing.JTextField();
        c2Lbl = new javax.swing.JLabel();
        c3FinalMark = new javax.swing.JTextField();
        cm3 = new javax.swing.JLabel();
        fm3 = new javax.swing.JLabel();
        c3CarryMark = new javax.swing.JTextField();
        c3Lbl = new javax.swing.JLabel();
        c4FinalMark = new javax.swing.JTextField();
        cm4 = new javax.swing.JLabel();
        fm4 = new javax.swing.JLabel();
        c4CarryMark = new javax.swing.JTextField();
        c4Lbl = new javax.swing.JLabel();
        c5FinalMark = new javax.swing.JTextField();
        cm5 = new javax.swing.JLabel();
        c1CarryMark = new javax.swing.JTextField();
        fm5 = new javax.swing.JLabel();
        c1Lbl = new javax.swing.JLabel();
        c5CarryMark = new javax.swing.JTextField();
        c1FinalMark = new javax.swing.JTextField();
        cm1 = new javax.swing.JLabel();
        c5Lbl = new javax.swing.JLabel();
        fm1 = new javax.swing.JLabel();
        c2FinalMark = new javax.swing.JTextField();
        cm2 = new javax.swing.JLabel();
        classPanel = new javax.swing.JPanel();
        classTxt = new javax.swing.JLabel();
        but_3a = new javax.swing.JRadioButton();
        but_3b = new javax.swing.JRadioButton();
        but_3c = new javax.swing.JRadioButton();
        but_3d = new javax.swing.JRadioButton();
        sgrHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deleteDataBtn = new javax.swing.JButton();
        clearAllDataBtn = new javax.swing.JButton();
        themeModeBtn = new javax.swing.JToggleButton();
        languageCb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(64, 23));

        sgrPanel.setBackground(new java.awt.Color(255, 255, 255));

        matricInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricInputActionPerformed(evt);
            }
        });

        matricsTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        matricsTxt.setText("Matric Number :");

        addDataBtn.setText("Add");
        addDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataBtnActionPerformed(evt);
            }
        });

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Matric", "CLASS", "C1 GPA", "C2 GPA", "C3 GPA", "C4 GPA", "C5 GPA", "CGPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displayTable);

        LogOutBtn.setText("Log out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        markPanel.setBackground(new java.awt.Color(255, 255, 255));

        fm2.setText("Final/ Test Mark :");

        c2CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2CarryMarkActionPerformed(evt);
            }
        });

        c2Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c2Lbl.setText("ISP 501");

        c3FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3FinalMarkActionPerformed(evt);
            }
        });

        cm3.setText("Carry Mark :");

        fm3.setText("Final/ Test Mark :");

        c3CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3CarryMarkActionPerformed(evt);
            }
        });

        c3Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c3Lbl.setText("ISP 500");

        c4FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4FinalMarkActionPerformed(evt);
            }
        });

        cm4.setText("Carry Mark :");

        fm4.setText("Final/ Test Mark :");

        c4CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4CarryMarkActionPerformed(evt);
            }
        });

        c4Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c4Lbl.setText("CTU 554");

        c5FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5FinalMarkActionPerformed(evt);
            }
        });

        cm5.setText("Carry Mark :");

        c1CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1CarryMarkActionPerformed(evt);
            }
        });

        fm5.setText("Final/ Test Mark :");

        c1Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c1Lbl.setText("CSC 465");

        c5CarryMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5CarryMarkActionPerformed(evt);
            }
        });

        c1FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1FinalMarkActionPerformed(evt);
            }
        });

        cm1.setText("Carry Mark :");

        c5Lbl.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        c5Lbl.setText("ICT 500");

        fm1.setText("Final/ Test Mark :");

        c2FinalMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2FinalMarkActionPerformed(evt);
            }
        });

        cm2.setText("Carry Mark :");

        javax.swing.GroupLayout markPanelLayout = new javax.swing.GroupLayout(markPanel);
        markPanel.setLayout(markPanelLayout);
        markPanelLayout.setHorizontalGroup(
            markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markPanelLayout.createSequentialGroup()
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cm3)
                            .addGroup(markPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cm4)
                                    .addComponent(cm5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c5CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c4CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(c3Lbl)
                    .addComponent(c4Lbl)
                    .addComponent(c5Lbl)
                    .addGroup(markPanelLayout.createSequentialGroup()
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cm1)
                            .addComponent(c1Lbl)
                            .addComponent(c2Lbl)
                            .addComponent(cm2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(markPanelLayout.createSequentialGroup()
                            .addComponent(fm3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c3FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markPanelLayout.createSequentialGroup()
                                .addComponent(fm2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c2FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(markPanelLayout.createSequentialGroup()
                                .addComponent(fm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c1FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(markPanelLayout.createSequentialGroup()
                            .addComponent(fm4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c4FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markPanelLayout.createSequentialGroup()
                        .addComponent(fm5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        markPanelLayout.setVerticalGroup(
            markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markPanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(markPanelLayout.createSequentialGroup()
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c3FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fm3))
                        .addGap(31, 31, 31)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c4FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fm4))
                        .addGap(37, 37, 37)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c5FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fm5)))
                    .addGroup(markPanelLayout.createSequentialGroup()
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c1Lbl)
                            .addGroup(markPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cm1)
                                    .addComponent(c1CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fm1)
                                    .addComponent(c1FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c2Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cm2)
                                    .addComponent(c2CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fm2)
                                    .addComponent(c2FinalMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addComponent(c3Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c3CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c4CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c5Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(markPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c5CarryMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm5))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        classPanel.setBackground(new java.awt.Color(255, 255, 255));

        classTxt.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        classTxt.setText("Class");

        buttonGroup1.add(but_3a);
        but_3a.setText("CS2663A");
        but_3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_3aActionPerformed(evt);
            }
        });

        buttonGroup1.add(but_3b);
        but_3b.setText("CS2663B");

        buttonGroup1.add(but_3c);
        but_3c.setText("CS2663C");

        buttonGroup1.add(but_3d);
        but_3d.setText("CS2663D");

        javax.swing.GroupLayout classPanelLayout = new javax.swing.GroupLayout(classPanel);
        classPanel.setLayout(classPanelLayout);
        classPanelLayout.setHorizontalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addComponent(classTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classPanelLayout.createSequentialGroup()
                        .addComponent(but_3a, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(but_3b, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(but_3c, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(but_3d, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        classPanelLayout.setVerticalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(classTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_3a)
                    .addComponent(but_3b)
                    .addComponent(but_3c)
                    .addComponent(but_3d))
                .addContainerGap())
        );

        sgrHeader.setBackground(new java.awt.Color(76, 79, 245));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SGR System");

        javax.swing.GroupLayout sgrHeaderLayout = new javax.swing.GroupLayout(sgrHeader);
        sgrHeader.setLayout(sgrHeaderLayout);
        sgrHeaderLayout.setHorizontalGroup(
            sgrHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgrHeaderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sgrHeaderLayout.setVerticalGroup(
            sgrHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgrHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        deleteDataBtn.setText("Delete");
        deleteDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDataBtnActionPerformed(evt);
            }
        });

        clearAllDataBtn.setText("Clear All");
        clearAllDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllDataBtnActionPerformed(evt);
            }
        });

        themeModeBtn.setText("Theme mode");
        themeModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeModeBtnActionPerformed(evt);
            }
        });

        languageCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Malay" }));
        languageCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sgrPanelLayout = new javax.swing.GroupLayout(sgrPanel);
        sgrPanel.setLayout(sgrPanelLayout);
        sgrPanelLayout.setHorizontalGroup(
            sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgrPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sgrPanelLayout.createSequentialGroup()
                        .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(sgrPanelLayout.createSequentialGroup()
                                .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matricInput, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(markPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 559, Short.MAX_VALUE))
                            .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(sgrPanelLayout.createSequentialGroup()
                        .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(sgrPanelLayout.createSequentialGroup()
                                .addComponent(matricsTxt)
                                .addGap(643, 643, 643)
                                .addComponent(languageCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(themeModeBtn))
                            .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sgrPanelLayout.createSequentialGroup()
                                    .addComponent(addDataBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(deleteDataBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(clearAllDataBtn))
                                .addGroup(sgrPanelLayout.createSequentialGroup()
                                    .addComponent(classPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(sgrHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sgrPanelLayout.setVerticalGroup(
            sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgrPanelLayout.createSequentialGroup()
                .addComponent(sgrHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matricsTxt)
                    .addComponent(themeModeBtn)
                    .addComponent(languageCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matricInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sgrPanelLayout.createSequentialGroup()
                        .addComponent(markPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(classPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sgrPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39)
                .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sgrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addDataBtn)
                        .addComponent(deleteDataBtn)
                        .addComponent(clearAllDataBtn)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sgrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sgrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricInputActionPerformed

    private void addDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataBtnActionPerformed
        // TODO add your handling code here:
        double[] gpa = new double[5];   
        
//        Calculate GPA members of 5
        gpa[0] = Integer.parseInt(c1CarryMark.getText()) + Integer.parseInt(c1FinalMark.getText());
        gpa[1] = Integer.parseInt(c2CarryMark.getText()) + Integer.parseInt(c2FinalMark.getText());
        gpa[2] = Integer.parseInt(c3CarryMark.getText()) + Integer.parseInt(c3FinalMark.getText());
        gpa[3] = Integer.parseInt(c4CarryMark.getText()) + Integer.parseInt(c4FinalMark.getText());
        gpa[4] = Integer.parseInt(c5CarryMark.getText()) + Integer.parseInt(c5FinalMark.getText());
        
        
        for(int i=0; i<gpa.length; i++){
            if(gpa[i] <= 100 && gpa[i] >=80){
                gpa[i] = 4.0;
                System.out.println(gpa[i]);
            }else if(gpa[i] < 80 && gpa[i] >= 75){
                gpa[i] = 3.67;
                System.out.println(gpa[i]);
            }else if(gpa[i] < 75 && gpa[i] >= 70){
                gpa[i] = 3.33;
            }else if(gpa[i] < 70 && gpa[i] >= 65){
                gpa[i] = 3.00;
            }else if(gpa[i] < 65 && gpa[i] >= 60){
                gpa[i] = 2.67;
            }else if(gpa[i] < 60 && gpa[i] >= 55){
                gpa[i] = 2.33;
            }else if(gpa[i] < 55 && gpa[i] >= 50){
                gpa[i] = 2.00;
            }else if(gpa[i] < 50 && gpa[i] >= 47){
                gpa[i] = 1.67;
            }else if(gpa[i] < 47 && gpa[i] >= 44){
                gpa[i] = 1.33;
            }else if(gpa[i] < 44 && gpa[i] >= 40){
                gpa[i] = 1.00;
            }else if(gpa[i] < 40 && gpa[i] >= 30){
                gpa[i] = 0.67;
            }else if(gpa[i] < 30){
                gpa[i] = 0.00;
            }
        }
        
        double cgpa = 0.0;
        
        for(int i=0; i<5; i++){
            cgpa += gpa[i];
        }
        
        cgpa = (cgpa/20)*4;
        
        String butClass;
        if(but_3a.isSelected()==true){
            butClass = "CS2663A";
        }else if(but_3b.isSelected()==true){
            butClass = "CS2663B";
        }else if (but_3c.isSelected()==true){
            butClass = "CS2663C";
        }else{ butClass = "CS2663D";}
        
//        data object untuk table
        String data[] = {matricInput.getText(),butClass ,Double.toString(gpa[0]), Double.toString(gpa[1]), Double.toString(gpa[2]), Double.toString(gpa[3]), Double.toString(gpa[4]), Double.toString(cgpa) };
        DefaultTableModel tblModel = (DefaultTableModel)displayTable.getModel();
        
//        insertion of data
        if(matricInput.getText().isEmpty()|| c1CarryMark.getText().isEmpty()|| c2CarryMark.getText().isEmpty()|| c3CarryMark.getText().isEmpty() || c4CarryMark.getText().isEmpty() || c5CarryMark.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some data not key in yet!");
        }else{
           
            tblModel.addRow(data);
        }      
       
        
                
    }//GEN-LAST:event_addDataBtnActionPerformed

    private void c1CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1CarryMarkActionPerformed

    private void c1FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FinalMarkActionPerformed

    private void c2FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2FinalMarkActionPerformed

    private void c2CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2CarryMarkActionPerformed

    private void c3FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3FinalMarkActionPerformed

    private void c3CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3CarryMarkActionPerformed

    private void c4FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4FinalMarkActionPerformed

    private void c4CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4CarryMarkActionPerformed

    private void c5FinalMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5FinalMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5FinalMarkActionPerformed

    private void c5CarryMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5CarryMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5CarryMarkActionPerformed

    private void but_3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_3aActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        Login login = new Login();
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void displayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayTableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tblModel = (DefaultTableModel)displayTable.getModel();
        
        String tblMatric = tblModel.getValueAt(displayTable.getSelectedRow(), 0).toString();
        String tblClass = tblModel.getValueAt(displayTable.getSelectedRow(), 1).toString();
        String tblC1 = tblModel.getValueAt(displayTable.getSelectedRow(), 2).toString();
        String tblC2 = tblModel.getValueAt(displayTable.getSelectedRow(), 3).toString();
        String tblC3 = tblModel.getValueAt(displayTable.getSelectedRow(), 4).toString();
        String tblC4 = tblModel.getValueAt(displayTable.getSelectedRow(), 5).toString();
        String tblC5 = tblModel.getValueAt(displayTable.getSelectedRow(), 6).toString();
        String tblCgpa = tblModel.getValueAt(displayTable.getSelectedRow(), 7).toString();
        
        
        
    }//GEN-LAST:event_displayTableMouseClicked

    private void deleteDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDataBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)displayTable.getModel();
        
        if(displayTable.getSelectedRowCount() == 1){
            tblModel.removeRow(displayTable.getSelectedRow());
        }else{
            if(displayTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is Empty!");
            }else{
                JOptionPane.showMessageDialog(this, "Please select single row for delete!");
            }
        }
    }//GEN-LAST:event_deleteDataBtnActionPerformed

    private void clearAllDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllDataBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)displayTable.getModel();
        
        int rowsToRemove = displayTable.getRowCount();
         
            if(displayTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is Empty!");
            }else{
                for(int i=0; i < rowsToRemove; i++){
                   tblModel.removeRow(0);
                }
                JOptionPane.showMessageDialog(this, "Clear all successful");
            }

    }//GEN-LAST:event_clearAllDataBtnActionPerformed

    private void themeModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeModeBtnActionPerformed
        // TODO add your handling code here:
         
        Color color = new Color(15,15,15);
        if(themeModeBtn.isSelected()){
            sgrPanel.setBackground(color);
            themeModeBtn.setBackground(color);
            themeModeBtn.setForeground(Color.white);          
            sgrHeader.setBackground(new Color(32,33,36));
            
            matricsTxt.setForeground(Color.WHITE);
            matricInput.setBackground(color);
            matricInput.setForeground(Color.white);
            
            markPanel.setBackground(color);
            markPanel.setForeground(Color.white);
            c1Lbl.setForeground(Color.white);
            c2Lbl.setForeground(Color.white);
            c3Lbl.setForeground(Color.white);
            c4Lbl.setForeground(Color.white);
            c5Lbl.setForeground(Color.white);
            
            cm1.setForeground(Color.white);
            cm2.setForeground(Color.white);
            cm3.setForeground(Color.white);
            cm4.setForeground(Color.white);
            cm5.setForeground(Color.white);
            
            fm1.setForeground(Color.white);
            fm2.setForeground(Color.white);
            fm3.setForeground(Color.white);
            fm4.setForeground(Color.white);
            fm5.setForeground(Color.white);
            
            c1CarryMark.setBackground(color);
            c1CarryMark.setForeground(Color.white);
            c2CarryMark.setBackground(color);
            c2CarryMark.setForeground(Color.white);
            c3CarryMark.setBackground(color);
            c3CarryMark.setForeground(Color.white);
            c4CarryMark.setBackground(color);
            c4CarryMark.setForeground(Color.white);
            c5CarryMark.setBackground(color);
            c5CarryMark.setForeground(Color.white);
            
            c1FinalMark.setBackground(color);
            c1FinalMark.setForeground(Color.white);
            c2FinalMark.setBackground(color);
            c2FinalMark.setForeground(Color.white);
            c3FinalMark.setBackground(color);
            c3FinalMark.setForeground(Color.white);
            c4FinalMark.setBackground(color);
            c4FinalMark.setForeground(Color.white);
            c5FinalMark.setBackground(color);
            c5FinalMark.setForeground(Color.white);
            
            classPanel.setBackground(color);
            classTxt.setForeground(Color.white);
            but_3a.setForeground(Color.white);
            but_3b.setForeground(Color.white);
            but_3c.setForeground(Color.white);
            but_3d.setForeground(Color.white);
            
            addDataBtn.setBackground(color);
            addDataBtn.setForeground(Color.white);
            deleteDataBtn.setBackground(color);
            deleteDataBtn.setForeground(Color.white);
            clearAllDataBtn.setBackground(color);
            clearAllDataBtn.setForeground(Color.white);
            LogOutBtn.setBackground(color);
            LogOutBtn.setForeground(Color.white);
            
        }else{
            sgrPanel.setBackground(Color.WHITE);
            themeModeBtn.setBackground(Color.white);
            themeModeBtn.setForeground(Color.black);
             sgrHeader.setBackground(new Color(76,79,245));
             
            matricsTxt.setForeground(Color.black);
            matricInput.setBackground(Color.white);
            matricInput.setForeground(Color.black);
            
            markPanel.setBackground(Color.white);
            markPanel.setForeground(Color.black);
            c1Lbl.setForeground(Color.black);
            c2Lbl.setForeground(Color.black);
            c3Lbl.setForeground(Color.black);
            c4Lbl.setForeground(Color.black);
            c5Lbl.setForeground(Color.black);
            
            cm1.setForeground(Color.black);
            cm2.setForeground(Color.black);
            cm3.setForeground(Color.black);
            cm4.setForeground(Color.black);
            cm5.setForeground(Color.black);
            
            fm1.setForeground(Color.black);
            fm2.setForeground(Color.black);
            fm3.setForeground(Color.black);
            fm4.setForeground(Color.black);
            fm5.setForeground(Color.black);
            
            c1CarryMark.setBackground(Color.white);
            c1CarryMark.setForeground(Color.black);
            c2CarryMark.setBackground(Color.white);
            c2CarryMark.setForeground(Color.black);
            c3CarryMark.setBackground(Color.white);
            c3CarryMark.setForeground(Color.black);
            c4CarryMark.setBackground(Color.white);
            c4CarryMark.setForeground(Color.black);
            c5CarryMark.setBackground(Color.white);
            c5CarryMark.setForeground(Color.black);
            
            c1FinalMark.setBackground(Color.white);
            c1FinalMark.setForeground(Color.black);
            c2FinalMark.setBackground(Color.white);
            c2FinalMark.setForeground(Color.black);
            c3FinalMark.setBackground(Color.white);
            c3FinalMark.setForeground(Color.black);
            c4FinalMark.setBackground(Color.white);
            c4FinalMark.setForeground(Color.black);
            c5FinalMark.setBackground(Color.white);
            c5FinalMark.setForeground(Color.black);
            
            classPanel.setBackground(Color.white);
            classTxt.setForeground(Color.black);
            but_3a.setForeground(Color.black);
            but_3b.setForeground(Color.black);
            but_3c.setForeground(Color.black);
            but_3d.setForeground(Color.black);
            
            addDataBtn.setBackground(Color.white);
            addDataBtn.setForeground(Color.black);
            deleteDataBtn.setBackground(Color.white);
            deleteDataBtn.setForeground(Color.black);
            clearAllDataBtn.setBackground(Color.white);
            clearAllDataBtn.setForeground(Color.black);
            LogOutBtn.setBackground(Color.white);
            LogOutBtn.setForeground(Color.black);
        }
        
        
    }//GEN-LAST:event_themeModeBtnActionPerformed

    private void languageCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageCbActionPerformed
        // TODO add your handling code here:
       if(languageCb.getSelectedItem() == "Malay"){
           matricsTxt.setText("Nombor Matrik :");
           cm1.setText("Penilaian Berterusan: ");
           cm2.setText("Penilaian Berterusan: ");
           cm3.setText("Penilaian Berterusan: ");
           cm4.setText("Penilaian Berterusan: ");
           cm5.setText("Penilaian Berterusan: ");
           fm1.setText("Markah Akhir: ");
           fm2.setText("Markah Akhir: ");
           fm3.setText("Markah Akhir: ");
           fm4.setText("Markah Akhir: ");
           fm5.setText("Markah Akhir: ");
           classTxt.setText("Kelas");
           addDataBtn.setText("Tambah");
           deleteDataBtn.setText("Buang");
           clearAllDataBtn.setText("Kosongkan Semua");
           themeModeBtn.setText("Mod Tema");
           LogOutBtn.setText("Log Keluar");
           
           
       }else if(languageCb.getSelectedItem() == "English"){
           matricsTxt.setText("Matric Number :");
           cm1.setText("Carry Mark: ");
           cm2.setText("Carry Mark: ");
           cm3.setText("Carry Mark: ");
           cm4.setText("Carry Mark: ");
           cm5.setText("Carry Mark: ");
           fm1.setText("Final/Test Mark: ");
           fm2.setText("Final/Test Mark: ");
           fm3.setText("Final/Test Mark: ");
           fm4.setText("Final/Test Mark: ");
           fm5.setText("Final/Test Mark: ");
           classTxt.setText("Class");
           addDataBtn.setText("Add");
           deleteDataBtn.setText("Delete");
           clearAllDataBtn.setText("Clear All");
           themeModeBtn.setText("Theme Mode");
           LogOutBtn.setText("Log out");
           
       }
    }//GEN-LAST:event_languageCbActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grading().setVisible(true);
            }
        });     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton addDataBtn;
    private javax.swing.JRadioButton but_3a;
    private javax.swing.JRadioButton but_3b;
    private javax.swing.JRadioButton but_3c;
    private javax.swing.JRadioButton but_3d;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c1CarryMark;
    private javax.swing.JTextField c1FinalMark;
    private javax.swing.JLabel c1Lbl;
    private javax.swing.JTextField c2CarryMark;
    private javax.swing.JTextField c2FinalMark;
    private javax.swing.JLabel c2Lbl;
    private javax.swing.JTextField c3CarryMark;
    private javax.swing.JTextField c3FinalMark;
    private javax.swing.JLabel c3Lbl;
    private javax.swing.JTextField c4CarryMark;
    private javax.swing.JTextField c4FinalMark;
    private javax.swing.JLabel c4Lbl;
    private javax.swing.JTextField c5CarryMark;
    private javax.swing.JTextField c5FinalMark;
    private javax.swing.JLabel c5Lbl;
    private javax.swing.JPanel classPanel;
    private javax.swing.JLabel classTxt;
    private javax.swing.JButton clearAllDataBtn;
    private javax.swing.JLabel cm1;
    private javax.swing.JLabel cm2;
    private javax.swing.JLabel cm3;
    private javax.swing.JLabel cm4;
    private javax.swing.JLabel cm5;
    private javax.swing.JButton deleteDataBtn;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel fm1;
    private javax.swing.JLabel fm2;
    private javax.swing.JLabel fm3;
    private javax.swing.JLabel fm4;
    private javax.swing.JLabel fm5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> languageCb;
    private javax.swing.JPanel markPanel;
    private javax.swing.JTextField matricInput;
    private javax.swing.JLabel matricsTxt;
    private javax.swing.JPanel sgrHeader;
    private javax.swing.JPanel sgrPanel;
    private javax.swing.JToggleButton themeModeBtn;
    // End of variables declaration//GEN-END:variables
}
